service: test-express

custom:
  # Our stage is based on what is passed in when running serverless commands, or falls back to what we have set in the provider section.
  stage: ${opt:stage, 'offline'}
  region: ${opt:region, 'us-east-1'}
  bundle:
    linting: false
  serverless-offline:
    httpPort: 4000
    noPrependStageInUrl: true

plugins:
  - serverless-dotenv-plugin
  - serverless-bundle
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 512
  timeout: 10
  logRetentionInDays: 7
  lambdaHashingVersion: 20201221 # https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2
  logs:
    httpApi: true
  httpApi:
    # Enable if desired, but note that there is a cost to this. Consider https://www.iopipe.com/features/ and other alternatives as well.
    # metrics: true
    cors: true

functions:
  app:
    handler: src/handler.handler
    events:
      - httpApi:
          path: '/{proxy+}'
          method: '*'
